[project]
name = "kuwahara-numba"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "kuwahara",
    "numba>=0.66.0",
]

[project.scripts]
bench-numba = "kuwahara_numba:app"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
kuwahara = { path = "../kuwahara", editable = true }

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.65",
]
